services:
  - type: web
    name: kumele-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    rootDir: backend-project
    plan: free
